### ISSUE TITLE
Cannot connect to VPN

### ISSUE THREAD

**Issue by Dailsks** [objective-see/LuLu#106]
I cannot connect to the PIA VPN servers while using Lulu 1.1.2. I have downgraded to Lulu 1.1.1 and it is once again working fine.

**Comment by nlierly** [comment]
Same issue with Tunnelblick - attempting 1.1.1 downgrade fixed issue

**Comment by objective-see** [comment]
This should be fixed in the [latest release](https://github.com/objective-see/LuLu/releases/tag/v1.2.0) (v1.2.0) :) 

Though please let me know if the this issue(s) persist!

**Comment by nchowinf** [comment]
Hi, this is still happening in v1.2.1 version. Once I disabled lulu, my vpn started working again.

**Comment by Afron-Lysias** [comment]
VPN connectivity lost after installing v.123.

**Comment by joesgrille** [comment]
I am on  1.2.3 and can't use PIA Private Internet Access. Suggestions?
